### PR TITLE
Created simple .editorconfig

### PR DESCRIPTION
**Pull request by markguinn**
For contributors who's editors/IDE support it, this will save us from having to push back on some style issues in PR's (primarily spaces => tabs). Check out http://editorconfig.org/ for more information.

I'll leave this open for a week or so for anyone to push back and/or add rules to the file as you see fit.

### CODE REVIEW

**Comment by markguinn** [comment]
Here are a few other examples from PHP projects. 

* CakePHP - https://github.com/cakephp/cakephp/blob/master/.editorconfig
* Drupal - http://cgit.drupalcode.org/drupal/tree/.editorconfig
* Symfony2 - https://github.com/symfony/symfony/blob/2.7/.editorconfig

Here's the full list: https://github.com/editorconfig/editorconfig/wiki/Projects-Using-EditorConfig

**Comment by jedateach** [comment]
Nice. Looks like a good initiative to get behind.
Any talk of this in SilverStripe community already?

**Comment by markguinn** [comment]
I've not seen it showing up on any other Silverstripe projects, no. I suppose one step beyond this is getting Scrutinizer to also check for style issues (where braces are placed, etc). The nice thing about this is that it's proactive if your editor supports it. So I could use PSR-2 on the rest of a project but any file in the shop folder will automatically use tabs, etc. 

I'd love to see it adopted more widely within the SS ecosystem. I wonder if it's worth raising on the dev list?

Note to self: before merging this we should also update the contributors doc asking them to install editor/ide plugins as needed.

**Comment by markguinn** [comment]
@jedateach are you happy with the state of this? If so I'll go ahead and squash these commits and merge.

**Comment by jedateach** [comment]
Yep, great. Go for it!

**Pull request merged**
