### PR TITLE
checkout components - fix payment type translation, add new address tran...

### PR DESCRIPTION
**Pull request by webtorque7**
Fixup translation for "Payment Type" on PaymentCheckoutComponent and add translation for "Create New Adress" on AddressBookCheckoutComponent

### CODE REVIEW

**Comment by markguinn** [comment]
Again, this looks good. It looks like there's one instance of spaces instead of tabs in this one as well. Thanks!

**Comment by nimeso** [comment]
So great to see heaps of people contributing! Thanks everyone!

On Sun, Apr 19, 2015 at 3:21 AM, Mark Guinn <notifications@github.com>
wrote:

> Again, this looks good. It looks like there's one instance of spaces
> instead of tabs in this one as well. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/burnbright/silverstripe-shop/pull/326#issuecomment-94173899>
> .
>



-- 
  q-p
 /\"/\
(`=*=') JAMIE BARKER
 ^---^`-._

   P: +64 3 338 2482
   Skype: jam.dog

**Comment by webtorque7** [comment]
Once again, my bad, had psr formatting setup. Should be fixed now.

**Comment by markguinn** [comment]
I absolutely agree, @nimeso. This is so good for the project.

**Pull request merged**
