### PR TITLE
Converted to PSR-2

### PR DESCRIPTION
**Pull request by helpfulrobot**
Hello!

I'm helpful robot. I noticed there were some deviations from PSR-2 in your code. The core committer team recently decided to transition SilverStripe Framework and CMS to PSR-2, and the [supported module standard](http://www.silverstripe.org/software/addons/supported-modules-definition) recommends following PSR-2. I've gone ahead and converted files in `code` and `tests` to PSR-2. If this sounds like something you'd like to merge then go right ahead! Feel free to ask questions or make suggestions for how I can help you more. I've been programmed with a wide range of responses.

Have a nice day! [gzzzzrrrkt]

### CODE REVIEW

**Comment by markguinn** [comment]
@anselmdk @wilr @jedateach @bummzack - any thoughts on this? I'd like to go to PSR-2 at some point but I'd imagined doing closer to the SS4.0 / namespaces / Shop 2.0 transition. Maybe it's smarter to just go for it now? It would mean all the existing PR's would likely need to be manually merged though as well as anyone who's got a branch going.

**Comment by bummzack** [comment]
I'd say go for the PSR-2 change now.
This is a PR that goes into `master` though and most of the new code/work is in `develop`. I'd suggest to pull in any open PRs that should be merged and then use a tool to convert everything in `develop` to PSR-2?

When talking about branches: When should we use `develop` and when `master` for PRs?

**Comment by markguinn** [comment]
Ah, that's a great point. Definitely can't merge this then. I'm starting to regret switching to gitflow and wondering if we should just switch back to a normal "github flow" with master being the default branch again. That said, for now all PR's should go against develop unless they're specifically a hotfix for the last release.

**Comment by bummzack** [comment]
I think it's not a big deal. Using `develop` is fine, maybe these rules just have to be visible, so that contributors can choose the appropriate branch. 
Converting to PSR-2 without the help of our friendly robot should be easy as well.

**Comment by anselmdk** [comment]
I see helpfulrobot has been very active with these things lately. I agree that this could be done on the development branch. If helpfulrobot is urging us to do this, it means that this is due to happen soon for SilverStripe core, so I'd say follow suit.
I agree with Mark, in that I'd prefer going with "github flow". That is `master` being the development branch. That's what the SilverStripe core modules are doing I think.

**Pull request closed without merging**
