### PR TITLE
Allow AddProductForm to be submitted via AJAX

### PR DESCRIPTION
**Pull request by adrian-stein**
To be used with PR on silverstripe-shop-ajax

### CODE REVIEW

**Comment by markguinn** [comment]
Thank you @adrian-stein! One little thing - the code you've submitted uses spaces instead of tabs. It seems like a nitpicky thing but over time the codebase would get really messy if we didn't keep on top of things like that. Do you want to fix that yourself (you can just amend your commit and then force push) or would you prefer I did and merged it manually?

**Comment by adrian-stein** [comment]
I can see if I can easily make the changes. Hopefully it is just the tab settings in my IDE!

**Comment by markguinn** [comment]
Which IDE are you using? If you download an http://editorconfig.org/ plugin for it, you won't have to change the settings. It should just use tabs when you're in the shop folder and spaces everywhere else.

**Comment by adrian-stein** [comment]
I am using PHP Storm. Im sure there is a setting somewhere in it. Just need to find it.

**Comment by markguinn** [comment]
I believe it's under Code Style. PHP Storm definitely has an editorconfig plugin which can make the whole thing more painless.

**Comment by adrian-stein** [comment]
I have installed the plug in. Do you have a .editorconfig file with all the code styles you would prefer to use so I make sure  have it set up exactly how you guys do it?

**Comment by markguinn** [comment]
There should be one already in the shop folder. I just realized there probably isn't one yet in the shop-ajax module. Feel free to copy the one over from shop and include it in your PR.

**Comment by adrian-stein** [comment]
Should be pushed now.

**Pull request merged**
