### PR TITLE
Change new Form to Form::create to enable injections.

### PR DESCRIPTION
**Pull request by hex0id**

### CODE REVIEW

**Comment by markguinn** [comment]
Thanks @hex0id. Could you squash those two commits into one so I can merge this?

**Comment by hex0id** [comment]
Hi Mark,

I am kinda new to this, I used github web interface to make changes. Is
there a way I can merge those commits via web interface? quick look on
interface have not gave a result...

On Wednesday, July 8, 2015, Mark Guinn <notifications@github.com> wrote:

> Thanks @hex0id <https://github.com/hex0id>. Could you squash those two
> commits into one so I can merge this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/burnbright/silverstripe-shop/pull/354#issuecomment-119472431>
> .
>


-- 
Regards, Alex.

**Comment by markguinn** [comment]
I don't think there's a way to do it from the web interface or the Github app. I would be happy to squash them for you and merge them if you'd like. You'll still get credit for the commit, but not the pull request as it will be merged manually. Is that ok? 

If not I'd be happy to help you do it manually (here's a good tutorial: https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/) or via a desktop app (SourceTree is free, Github-aware, and it's pretty easy to squash commits).

**Comment by hex0id** [comment]
yeah I'll try those tutorials, I plan to make some commits from time to
time, so tutorial will be useful for me. Thanks

**Comment by markguinn** [comment]
Great. Let me know if you get stuck. The tutorial says not to do squash commits that you've already pushed - which is good practice in general - but in this case it's fine. When you push the squashed commit you'll need to use `git push origin patch-3 --force` to make it overwrite the previous two commits with the newly squashed one.

**Comment by markguinn** [comment]
@hex0id would you like me to go ahead and handle this so we can get it merged? Or is there anything I can do to help you?

**Comment by hex0id** [comment]
hi Mark,

Thanks for reminding me! I completely forgot about that. Yes please, I
overplanned my time.

On Wed, Aug 19, 2015 at 6:53 AM, Mark Guinn <notifications@github.com>
wrote:

> @hex0id <https://github.com/hex0id> would you like me to go ahead and
> handle this so we can get it merged? Or is there anything I can do to help
> you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/burnbright/silverstripe-shop/pull/354#issuecomment-132538953>
> .
>



-- 
Regards, Alex.

**Comment by markguinn** [comment]
This is now merged manually. Thanks @hex0id!

**Pull request closed without merging**
