### PR TITLE
Add Locale information to Order. Fixes #403

### LINKED ISSUE #403: Order complete callbacks should be locale aware.
Maybe add a `Locale` field to `Order` to keep track of the order locale?
This is needed to ensure correct localization of e-mails and other content that might get generated upon order completion. It's also valuable for customer-relations.

Other things to consider are the Locale support of omnipay itself: https://github.com/thephpleague/omnipay/issues/279
But maybe these can be added/tracked individually.

The different translation modules (Translatable, Fluent) should be considered when implementing this.

### PR DESCRIPTION
**Pull request by bummzack**
Added locale db-field to order.
Added helper tools to get/set current locale.
Ensure locale is properly saved while an order is in `Cart` state.
Install the saved locale during order processing.
Install order-locale for ajax requests to ensure ajax response is rendered with the proper locale.

### CODE REVIEW

**Comment by bummzack** [comment]
@markguinn This could probably also be merged into `develop`. What do you think?

**Comment by markguinn** [comment]
I don't see any breaking changes there so it could go in the next minor version. Assuming you started this on the 2.0 branch, I'm not sure the best way to move it to develop. If we just merge it, we'll also merge all the history on develop-2.0 which we don't want to do. I think you could start a new branch and cherry-pick it though. I think this would be great to have on the main branch if you can figure out the git-acrobatics.

**Comment by bummzack** [comment]
@markguinn ok I'll merge this one and try to cherry-pick it into `develop` as well if that's fine with you.

**Comment by markguinn** [comment]
That's great. Thanks!

**Pull request merged**
